### ISSUE TITLE
Missing billing references

### ISSUE THREAD

**Issue by mgenfinity** [sveawebpay/svea-sdk-dotnet#331]
Please add BillingReferences mentioned here https://paymentsdocs.svea.com/docs/manage-order/getting_order_information/
to the PaymentAdminApi.Models.Order model returned from GetOrder.

**Comment by SebastianRuthstrom** [comment]
Hi @mgenfinity 
This is resolved in v4.5.0.

Best regards, Sebastian

**Comment by mgenfinity** [comment]
@SebastianRuthstrom It doesn't seem like the changes are part of 4.5.0. It looks to me like you forgot to merge in the changes. v4.5.0 is the same as v.4.4.0

**Comment by mgenfinity** [comment]
> Hi [@mgenfinity](https://github.com/mgenfinity) This is resolved in v4.5.0.
> 
> Best regards, Sebastian

@SebastianRuthstrom 
Can you check the update? It doesn't look like the changes were included in the nuget.

**Comment by SebastianRuthstrom** [comment]
Hi @mgenfinity sorry for late response, we will take a look at it ASAP

**Comment by SebastianRuthstrom** [comment]
@mgenfinity we did a new release yesterday where it should be solved!
